### ISSUE TITLE
Address slow integration tests on CI

### ISSUE THREAD

**Issue by fridrik01** [consensus-shipyard/ipc#685]
I think we should address the slow integration/e2e tests on CI, its creeping over 40+ minutes. 

The issue with this is not that the actual tests are so slow, but the whole compile/build steps are. 

Some ideas:
- Try caching all the rust dependencies (we aren't upgrading them so often), the contracts, etc.
- Commit contract artifacts to git repo, then we don't need to compile them (this takes many minutes on CI)
- Consider whether downloading prebuilt docker container (which we built each time PR gets merged to main) would speed things up for us. 
- more ideas?

**Comment by nahsi** [comment]
> Commit contract artifacts to git repo
You can also cache them like [this](https://github.com/fluencelabs/deal/blob/main/.github/workflows/artifacts.yml#L61)

**Comment by aakoshh** [comment]
Caching used to work, but I don't see the big caches updated any more at https://github.com/consensus-shipyard/ipc/actions/caches, they are months old :thinking: 

* For Rust, it's set up [here](https://github.com/consensus- shipyard/ipc/blob/aad693d88b26a5845f3fdab69a3e0406f9c41ddc/.github/workflows/fendermint-test.yaml#L78-L85) and [here](https://github.com/consensus-shipyard/ipc/blob/aad693d88b26a5845f3fdab69a3e0406f9c41ddc/.github/workflows/fendermint-publish.yaml#L37-L46)
* The contract compilation output is cached [here](https://github.com/consensus-shipyard/ipc/blob/aad693d88b26a5845f3fdab69a3e0406f9c41ddc/.github/workflows/fendermint-test.yaml#L87-L91) 

There is a mechanism to cache compiled dependencies in docker build [here](https://github.com/consensus-shipyard/ipc/blob/aad693d88b26a5845f3fdab69a3e0406f9c41ddc/fendermint/docker/builder.ci.Dockerfile#L15-L73), however I'm afraid because the latest docker image isn't pulled in the beginning we don't get the benefit of the cached layers. This should be an easy fix.

**Comment by aakoshh** [comment]
Perhaps I misunderstood how [updating](https://github.com/consensus-shipyard/ipc/blob/aad693d88b26a5845f3fdab69a3e0406f9c41ddc/.github/actions/setup-cache/action.yaml#L23) works. 

We have this cache:
```
fendermint-End-to-End-ubuntu-latest-stable-7d402d69c6c8750e26ed2754c0613259102897fb23e7feb7a8216a1267a92f87-4b4286f6160f9f55d7c0f24fb92f6bb56fa2f75ebde01e3d985d65c519a7b8ea
310 MB cached 2 months ago
```

I see it's being restored:
```
with:
    release-name: v0.3.1
    cache-key: fendermint-Test-ubuntu-latest-stable-7d402d69c6c8750e26ed2754c0613259102897fb23e7feb7a86a1267a92f87
    cache-suffix: fe0f11b53b2c7d9ef5a7886545c1f09fda06ba848c45ef07be1143581781b469
    cache-update: false
    cache-date: false
    cache-save: true
  env:
    CARGO_INCREMENTAL: 0
    SCCACHE_CACHE_SIZE: 10G
    CC: sccache clang
    CXX: sccache clang++
    PROFILE: ci
    BUILDX_FLAGS: --cache-from=type=gha --cache-to=type=gha,mode=max
    RUST_BACKTRACE: full
    RUSTFLAGS: -Dwarnings
    CARGO_TERM_COLOR: always
Using restoreKey: fendermint-Test-ubuntu-latest-stable-7d402d69c6c8750e26ed2754c0613259102897fbe7feb7a8216a1a92f87
```

And it finds the old cache:
```
Cache restored successfully
Cache restored from fendermint-Test-ubuntu-latest-stable-7d402d69c6c8750e26ed2754c0613259102897fb23e7feb7a8216a1267a92f87-4b4286f6160f9f55d7c0f24fb92f6bb56fa2f75ebde01e3d985dc519a7b8ea.
```

I only use the prefix (which only changes with the task and the rust toolchain) to restore, so it finds this cache, and the suffix (depends on the Cargo.lock file) is different, however in the end it won't update:

```
cacheKey: fendermint-Test-ubuntu-latest-stable-7d402d69c6c8750e26ed2754c0613259102897fb23e7feb7a8216a1267a92f87-4b4286f6160f9f55d7c0f24fb92f6bb56fa2f75ebde01e3d985d65c519a7b8ea
Aborting, shouldUpdateCache: false
```

So the cache key at the end doesn't consider the suffix :thinking: 

I'll have to have another look at https://github.com/consensus-shipyard/sccache-action/tree/fendermint
